### PR TITLE
Updating kafka service write location

### PR DESCRIPTION
**Pull request by MadhuriArugula**
These PR changes are made to resolve the issue #90 

Kafka write location needs to be updated to ensure that the mount point in helm charts and kafka service topics/partitions write location are not same to avoid known issue of lost+found directory https://github.com/ches/docker-kafka/issues/28 

These changes are backward compatible as we are creating a sub folder under /opt/pega/kafkadata

Refer BUG-575909 for more details.

### CODE REVIEW

**Review by Saurabh-16 — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting pipeline for PR validation -> PR-87-1

**Comment by pegaautomationuser** [comment]
Starting pipeline for PR validation -> PR-87-2

**Comment by pegaautomationuser** [comment]
Starting pipeline for PR validation -> PR-87-3

**Review by dcasavant — APPROVED** [review]

**Comment by pegaautomationuser** [comment]
Starting pipeline for PR validation -> PR-87-1

**Comment by pegaautomationuser** [comment]
Starting pipeline for PR validation -> PR-87-2

**Comment by pegaautomationuser** [comment]
Starting pipeline for PR validation -> PR-87-3

**Comment by pegaautomationuser** [comment]
Starting pipeline for PR validation -> PR-87-3

**Comment by pegaautomationuser** [comment]
Starting pipeline for PR validation -> PR-87-4

**Comment by MadhuriArugula** [comment]
#90

**Pull request merged**
