### PR TITLE
BUG-868079 Add the option to configure keystore and truststore type for Cassandra connection 

### PR DESCRIPTION
**Pull request by wonim2022**

### CODE REVIEW

**Review by taz-pega-work — APPROVED** [review]
looks good! nice job!

**Comment by wonim2022** [comment]
@kingakowalska1 Please review this PR when you have a moment

**Review by kingakowalska1 — APPROVED** [review]
Looks great. thanks!

**Comment by taz-pega-work** [comment]
squashing and merging at the request of Paul Bayliss, Product Owner for Cassandra

**Comment by taz-pega-work** [comment]
squashing and merging at the request of Paul Bayliss, Product Owner for Cassandra

**Pull request merged**
