### PR TITLE
BUG-528213 enabled readwrite access to webapps folder

### PR DESCRIPTION
**Pull request by agellanki**
Enabled read write access to web apps folder due to #BUG-528213

### CODE REVIEW

**Comment by MadhuriArugula** [comment]
ISSUE #51

**Comment by agellanki** [comment]
As per John comments in the #BUG-528211

**Comment by Emilio-Pega** [comment]
@agellanki John's comment was SPECIFIC to the tempdir not the WEBAPPS Dir.  Why was thei PR closed for a completely different issue? 

cc @dcasavant

**Comment by Emilio-Pega** [comment]
To be clear, I just want a better understanding regarding why this was closed because the referenced comments don't have anything to do with this specific issue...

**Comment by zitikay** [comment]
When merging master to handle conflict, also updated README to address issue #62

**Review by khick77 — APPROVED** [review]

**Review by APegaDavis — APPROVED** [review]

**Review by misterdorito — APPROVED** [review]

**Review by dcasavant — APPROVED** [review]

**Pull request merged**
