### PR TITLE
using tomcat8-jre8

### PR DESCRIPTION
**Pull request by viper0131**
Be prepared for the future....

### CODE REVIEW

**Comment by dcasavant** [comment]
Using tomcat 8 introduced some issues (could just be the build env).  Will get them resolved soon, but for now let's move to Java 8 without it.  

PS- sorry for the delay.  I missed the notification on this PR.

**Comment by viper0131** [comment]
@dcasavant , what issues did you encounter with tomcat8? I'm running a few months now on tomcat8-jre8. Didn't find any issues.

**Comment by dcasavant** [comment]
@viper0131 I was unable to start for some reason.  Like I said, it may just be a local issue.  I have a roadmap that includes CI/CD for this project as well as tomcat 8 support so this won't be an issue going forward.

**Comment by viper0131** [comment]
@dcasavant, found a change I did to get tomcat 8 working.

In the server.xml you have to remove the Jasper reference.

I do it in my own entrypoint script:
 
`#
# remove jasper lib from server.xml if running on tomcat8
#
if [ "${TOMCAT_MAJOR}" = "8" ]; then
  sed -i "s|^.*Jasper.*$||" /usr/local/tomcat/conf/server.xml
fi`

**Comment by dcasavant** [comment]
An update that includes the latest tomcat is part of #19 which will be merged as soon as it is ready.

This PR should no longer be needed.  Please reopen if you disagree!

**Pull request closed without merging**
